In [2]:
import yfinance as yf
import pandas as pd
import numpy as np
import requests
import os.path
import time
import json
import csv
import re
import os
from datetime import datetime
from tqdm import tqdm

In [6]:
ACL19_dir = r"D:\ACL19_Release"
MAEC_dir = r"D:\MAEC"
sp1500_dir = r"D:\sp1500"

alpha_dir = 'data/alpha_advantage/{}.csv' #.format(ticker)
alpha_columns = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Dividend Amount', 'Split Coefficient']

# company_ticker = pd.read_csv('data/company_ticker.csv') # special file
# alpha_advantage = pd.read_csv('data/alpha_advantage_Adj.csv')
targets = pd.read_csv('data/targets.csv')
targets.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            572 non-null    object
 1   Date               572 non-null    object
 2   Ticker             572 non-null    object
 3   3_day              572 non-null    float64
 4   7_day              572 non-null    float64
 5   15_day             572 non-null    float64
 6   30_day             572 non-null    float64
 7   3_day_Yahoo        572 non-null    float64
 8   7_day_Yahoo        572 non-null    float64
 9   15_day_Yahoo       572 non-null    float64
 10  30_day_Yahoo       572 non-null    float64
 11  3_day_diff         562 non-null    float64
 12  7_day_diff         562 non-null    float64
 13  15_day_diff        562 non-null    float64
 14  30_day_diff        562 non-null    float64
 15  3_day_pct_change   556 non-null    float64
 16  7_day_pct_change   560 non-null    float64
 17  15_day_pct_change  560 non-null    float64
 18  30_day_pct_change  572 non-null    float64
dtypes: float64(16), object(3)
memory usage: 85.0+ KB

In [26]:
def each_row(row):
    Company = row['Company']
    Date = row['Date'].replace('-', '') 

    text_path = f"D:/ACL19_Release/{Company}_{Date}/TextSequence.txt"
    # with open(text_path, 'r') as file:
    with open(text_path, 'r', encoding='utf-8', errors='replace') as file:
        for i, line in enumerate(file, start= 1):
            #I'll do something with this 
            text_length = i

    audio_dir = f"D:/ACL19_Release/{Company}_{Date}/CEO"
    if os.path.exists(audio_dir):
        audio_length = len(os.listdir(audio_dir))
    return text_length, audio_length

targets[['text_length', 'audio_length']] = targets.apply(each_row, axis=1, result_type='expand')

In [28]:
targets[targets['text_length']!= targets['audio_length']]

,Company,Date,Ticker,3_day,7_day,15_day,30_day,3_day_Yahoo,7_day_Yahoo,15_day_Yahoo,...,3_day_diff,7_day_diff,15_day_diff,30_day_diff,3_day_pct_change,7_day_pct_change,15_day_pct_change,30_day_pct_change,text_length,audio_length
428,Regeneron,2017-08-03,REGN,1.166726,4.644664,4.098558,10.515301,1.166743,4.644669,4.098564,...,-0.000017,-0.000005,-0.000006,-7.674749e-07,-0.001480,-0.000104,-0.000135,-0.000007,134,135
535,Ventas Inc,2017-10-27,VTR,0.386759,0.451387,0.611748,0.553543,0.389731,0.454848,0.616439,...,-0.002971,-0.003462,-0.004691,-4.245520e-03,-0.762425,-0.761024,-0.761037,-0.761134,158,159

In [16]:
targets.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            572 non-null    object
 1   Date               572 non-null    object
 2   Ticker             572 non-null    object
 3   3_day              572 non-null    float64
 4   7_day              572 non-null    float64
 5   15_day             572 non-null    float64
 6   30_day             572 non-null    float64
 7   3_day_Yahoo        572 non-null    float64
 8   7_day_Yahoo        572 non-null    float64
 9   15_day_Yahoo       572 non-null    float64
 10  30_day_Yahoo       572 non-null    float64
 11  3_day_diff         562 non-null    float64
 12  7_day_diff         562 non-null    float64
 13  15_day_diff        562 non-null    float64
 14  30_day_diff        562 non-null    float64
 15  3_day_pct_change   556 non-null    float64
 16  7_day_pct_change   560 non-null    float64
 17  15_day_pct_change  560 non-null    float64
 18  30_day_pct_change  572 non-null    float64
 19  text_length        572 non-null    int64
 20  audio_length       572 non-null    int64
dtypes: float64(16), int64(2), object(3)
memory usage: 94.0+ KB